---
- hosts: 172.31.22.237
  become: yes
  tasks: 
  - name: i want to execute linux command 
    command: hostname -f
    register: myresult

  - name: i want to see(dispaly) first task reuslt 
    debug: 
       msg: "{{myresult}}"