---
- hosts: 172.31.22.237
  become: yes
  tasks: 
  - name: i want to execute linux command 
    command: hostname -f
    register: myresult

  - name: i want to see(dispaly) first task reuslt 
    debug: 
       msg: "{{myresult}}"
  - name: install git 
    apt: 
      name: git 
      state: present 
    when: myresult.stderr=!

  - name: install tree
    apt:  
      name: tree
      state: present
    when: myresult.stderr==""