---
- hosts: 172.31.22.237
  become: yes
  tasks: 
  - name: i want to create folder 
    file:
      path: /home/maha/myfolder
      state: directory

  - include_tasks: myfile.yml

  - name: copy the file into node side
    copy: 
      src: mytestfile
      dest: /home/maha/myfolder

  - name: i want to download internet file
    get_url:
       url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.10/bin/apache-tomcat-10.0.10.tar.gz
       dest: /home/maha/myfolder/apache-tomcat-10.0.10.tar.gz
       force_basic_auth: yes

  - name: i want install apache2 webserver 
    apt:
      name: apache2
      state: present 
   

  