---
- hosts: 172.31.22.237
  become: yes
  tasks: 
  - name: i want to create folder 
    file:
      path: /home/maha/myfolder
      state: directory

  - name: i want to creae a file 
    file:
       path: /home/maha/myfolder/myfirstfile
       state: touch