---
# tasks file for testts
- include_tasks: myjava.yml
- include_tasks: download.yml
- include_tasks: Permission.yml
- include_tasks: linkfiles.yml
- include_tasks: dashboard.yml
- include_tasks: starttomcat.yml